services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Progress\Framework\Controller\:
    resource: '../../../src/Progress/Framework/Controller/'
    tags: [ 'controller.service_arguments' ]