parameters:
  aws.region.west: 'eu-west-1'
  aws.dynamodb.endpoint: '%env(AWS_DYNAMODB_ENDPOINT)%'
  aws.sqs.endpoint: '%env(AWS_SQS_ENDPOINT)%'
  bucket.name: '%env(AWS_S3_BUCKET_NAME)%'

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  aws.credentials:
    class: Aws\Credentials\Credentials
    arguments:
      - '%env(AWS_ACCESS_ID)%'
      - '%env(AWS_SECRET_KEY)%'

  SharedKernel\Infrastructure\Aws\DynamoDb\Factory\ClientFactory: ~

  aws.dynamodb.marshaler:
    class: Aws\DynamoDb\Marshaler

  aws.dynamodb.client.west:
    class: Aws\DynamoDb\DynamoDbClient
    factory: [ '@SharedKernel\Infrastructure\Aws\DynamoDb\Factory\ClientFactory', 'build' ]
    arguments:
      - '@aws.credentials'
      - '%aws.region.west%'
      - '%aws.dynamodb.endpoint%'

  aws.dynamodb.day-completed:
    class: SharedKernel\Infrastructure\Aws\DynamoDb\DynamoDb
    arguments:
      - '@aws.dynamodb.client.west'
      - '@aws.dynamodb.marshaler'
      - 'day-completed'

  SharedKernel\Application\Aws\DynamoDb\KeyValueDatabaseClient $dayCompletedDb: '@aws.dynamodb.day-completed'

  aws.sqs.client:
    class: Aws\Sqs\SqsClient
    factory: [ 'SharedKernel\Infrastructure\Aws\Sqs\ClientFactory', 'build' ]
    arguments:
      - '@aws.credentials'
      - '%aws.region.west%'
      - '%aws.sqs.endpoint%'

  aws.s3.eu-west:
    class: Aws\S3\S3Client
    factory: [ 'SharedKernel\Infrastructure\Aws\S3\Factory\ClientFactory', 'build' ]
    arguments:
      - '@aws.credentials'
      - '%aws.region.west%'

  Progress\Application\Service\FilesStorage: '@Progress\Infrastructure\Aws\S3\S3FilesStorage'

  Progress\Infrastructure\Aws\S3\S3FilesStorage:
    arguments:
      $client: '@aws.s3.eu-west'
      $bucketName: '%bucket.name%'

  SharedKernel\Application\Aws\Queue\Process\Consumer\UpdateDayCompletion:
    tags:
      - { name: 'process.consumer' }

  SharedKernel\Application\Aws\Queue\Process\Transport: '@SharedKernel\Infrastructure\Aws\Sqs\Sqs'

  SharedKernel\Infrastructure\Aws\Sqs\Sqs:
    arguments:
      - '@aws.sqs.client'

  SharedKernel\Infrastructure\Symfony\Command\QueueConsumeCommand:
    tags:
      - { name: 'console.command', command: 'queue:consume'}

  SharedKernel\Infrastructure\Symfony\Command\FinishDayCommand:
    tags:
      - { name: 'console.command', command: 'app:finish:day' }

  SharedKernel\Application\Aws\Queue\Process\ConsumerResolver:
    arguments:
      - !tagged_iterator 'process.consumer'

  SharedKernel\Application\Aws\Queue\Process\Process: ~
  SharedKernel\Application\Aws\Queue\Process\Dispatcher: ~